[CmdletBinding()]
param(
  [string]$OutputPath = '',
  [string]$TagPattern = 'v0.1.*',
  [string]$NextTag = ''
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Get-RequiredCommand {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Name
  )

  $command = Get-Command $Name -ErrorAction SilentlyContinue | Select-Object -First 1
  if ($null -eq $command) {
    throw "Required command '$Name' was not found on PATH."
  }

  return $command.Source
}

$repoRoot = Split-Path -Parent $PSScriptRoot
if ([string]::IsNullOrWhiteSpace($OutputPath)) {
  $OutputPath = Join-Path $repoRoot 'docs\releases.md'
}
$outputDir = Split-Path -Parent $OutputPath
if (-not (Test-Path $outputDir)) {
  New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}

$git = Get-RequiredCommand 'git'

$tagsAsc = & $git -C $repoRoot tag --list $TagPattern --sort=v:refname
if (-not $tagsAsc) {
  throw "No tags matched pattern '$TagPattern'."
}
$tagListAsc = @($tagsAsc)
$tagListDesc = & $git -C $repoRoot tag --list $TagPattern --sort=-v:refname
if (-not $tagListDesc) {
  throw "No tags matched pattern '$TagPattern'."
}

$sectionMap = @{}
$prev = $null
foreach ($tag in $tagListAsc) {
  if ($prev -eq $null) {
    $sectionMap[$tag] = @('Initial release.')
  } else {
    $subjects = & $git -C $repoRoot log --pretty=format:%s "$prev..$tag"
    if (-not $subjects) {
      $subjects = @('No commits found.')
    }
    $sectionMap[$tag] = @($subjects)
  }
  $prev = $tag
}

$latestTag = $tagListDesc | Select-Object -First 1
$unreleased = & $git -C $repoRoot log --pretty=format:%s "$latestTag..HEAD"
if (-not $unreleased) {
  $unreleased = @('No unreleased changes.')
}
$nextNotes = @()
if (-not [string]::IsNullOrWhiteSpace($NextTag)) {
  if ($unreleased.Count -eq 1 -and $unreleased[0] -eq 'No unreleased changes.') {
    $nextNotes = @('No commits found.')
  } else {
    $nextNotes = @($unreleased)
  }
  $unreleased = @('No unreleased changes.')
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('# Releases')
$lines.Add('')
$lines.Add('Auto-generated by scripts/update-release-notes.ps1. Edit GitHub release bodies for narrative notes; this file tracks commit-level changes per tag.')
$lines.Add('')
$lines.Add('## Unreleased')
foreach ($note in $unreleased) {
  $lines.Add("- $note")
}
$lines.Add('')

if ($unreleased.Count -gt 0 -and $unreleased[0] -ne 'No unreleased changes.') {
  $lines.Add('## Next')
  foreach ($note in $unreleased) {
    $lines.Add("- $note")
  }
  $lines.Add('')
}

if ($nextNotes.Count -gt 0) {
  $lines.Add("## $NextTag")
  foreach ($note in $nextNotes) {
    $lines.Add("- $note")
  }
  $lines.Add('')
}

foreach ($tag in $tagListDesc) {
  $lines.Add("## $tag")
  foreach ($note in $sectionMap[$tag]) {
    $lines.Add("- $note")
  }
  $lines.Add('')
}

$lines | Set-Content -Path $OutputPath -Encoding ASCII
Write-Host "Wrote release notes to $OutputPath"
